---
name: Check PRs to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-base-branch:
    if: github.head_ref != "testing"
    runs-on: ubuntu-latest
    steps:
      - uses: a-b-r-o-w-n/check-base-branch-action@v1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          protected-branches: "main"
          default-branch: "testing"
          update-branch: true
